[project]
name = "beat-book-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "csvkit>=2.2.0",
    "datasette>=0.65.2",
    "llm>=0.28",
    "newspaper4k>=0.9.4.1",
    "sqlite-utils>=3.39",
]
